export const authors: Record<string, string> = {
	"আনিকা তুবা": "anika-tuba",
	"আরিফা জামান": "arifa-jaman",
	"উম্ম আইশা": "umm-aisha",
	"উম্ম খালেদ": "umm-khaled",
	"উম্মু মুসা": "ummu-musa",
	"উম্মে আহমাদ": "umme-ahmad",
	"উম্মে ফাতিমা": "umme-fatima",
	"উম্মে মুসআব": "umme-musab",
	"জুমানা পুষ্প": "jumana-pushpa",
	"তুহফা বিনতে কবির": "tuhfa-binte-kabir",
	"নাইমা মেরিন মল্লিকা": "naima-marin-mallika",
	"নিশাত তাম্মিম": "nishat-tammim",
	"নূরে জাহান মুনিয়া": "nure-jahan-muniya",
	"প্রীতি": "preeti",
	"ফাতেমা তুয জোহরা": "fatema-tuz-zohra",
	"বিনতে আফজাল": "binte-afzal",
	"বিনতে আব্দুল্লাহ": "binte-abdullah",
	"মনীষা বর্ষা": "monisha-borsha",
	"মাহবুব আরা বেগম": "mahbub-ara-begum",
	"মাহবুবা সুলতানা প্রাঙ্গন": "mahbuba-sultana-prangan",
	"রানিয়া কবির": "rania-kabir",
	"রেবেকা জামান বিভা": "rebecca-jaman-biva",
	"শামীমা নিম্মি": "shamima-nimmi",
	"সাদিয়া সুলতানা": "sadia-sultana",
	"সানজিদা শারমিন": "sanjida-sharmin",
	"সানজিদা সাদাকা": "sanjida-sadaka",
	"সাবরিন সুলতানা তাকিয়া": "sabrin-sultana-takia",
	"সামান্থা সাবেরিন মাহী": "samanta-sabrin-mahi",
	"সায়্যিদা হাসনা বিনতে হাফিজ": "sayyida-hasna-binte-hafiz",
	"সালমা জাহান": "salma-jahan",
	"সিন্থিয়া শারমিন স্নিগ্ধা": "sinthia-sharmin-snigdha"
};

export const categories: Record<string, string> = {
	"ক্যাটাগরিহীন": "uncategorized",
	"দাম্পত্য": "marriage",
	"নারীবাদ": "feminism",
	"পর্দা": "purdah",
	"শরীয়াহ": "shariah",
	"শিক্ষা ও ক্যারিয়ার": "education-career",
	"সংক্ষিপ্ত": "brief",
	"সচেতনতা": "awareness",
	"সাম্প্রতিক": "recent"
};
